// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7HXyQXIH7j-mdSISdW5Bua8FVD5i7fu8',
    appId: '1:704625631684:web:6d1c99f2d1f49426c90491',
    messagingSenderId: '704625631684',
    projectId: 'spinza-5a6b8',
    authDomain: 'spinza-5a6b8.firebaseapp.com',
    storageBucket: 'spinza-5a6b8.firebasestorage.app',
    measurementId: 'G-EW657V1BJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoKwuf_Bn4JU90a-OLzZ9CMp39qOJi8aA',
    appId: '1:704625631684:android:99590a4ef3a47a58c90491',
    messagingSenderId: '704625631684',
    projectId: 'spinza-5a6b8',
    storageBucket: 'spinza-5a6b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPCzlzFqEnABwfOHY3lK2wJUA4bniLD3I',
    appId: '1:704625631684:ios:f4ce279c9c04928fc90491',
    messagingSenderId: '704625631684',
    projectId: 'spinza-5a6b8',
    storageBucket: 'spinza-5a6b8.firebasestorage.app',
    iosBundleId: 'com.example.spinza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPCzlzFqEnABwfOHY3lK2wJUA4bniLD3I',
    appId: '1:704625631684:ios:f4ce279c9c04928fc90491',
    messagingSenderId: '704625631684',
    projectId: 'spinza-5a6b8',
    storageBucket: 'spinza-5a6b8.firebasestorage.app',
    iosBundleId: 'com.example.spinza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7HXyQXIH7j-mdSISdW5Bua8FVD5i7fu8',
    appId: '1:704625631684:web:de779746805cffccc90491',
    messagingSenderId: '704625631684',
    projectId: 'spinza-5a6b8',
    authDomain: 'spinza-5a6b8.firebaseapp.com',
    storageBucket: 'spinza-5a6b8.firebasestorage.app',
    measurementId: 'G-NZPNNXR3PP',
  );
}
